Blog/Blog/Models/BlogPostRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Blog.Data;
using Blog.Domain;

namespace Blog.Web.Models
{
  public class BlogPostRepository
  {
    private readonly BlogContext _blogContext;

    public BlogPostRepository(BlogContext context)
    {
      _blogContext = context;
    }

    public void AddPost(BlogPost post)
    {
      post.PostDate = DateTime.Now;
      _blogContext.BlogPosts.Add(post);
      _blogContext.SaveChanges();
    }

    public void RemovePost(int id)
    {
      var post = _blogContext.BlogPosts.Find(id);
      
      if (post != null)
      {
        _blogContext.BlogPosts.Remove(post);
        _blogContext.SaveChanges();
      }
    }

    public BlogPost PostWithHighestRating()
    {
      var post = _blogContext.BlogPosts
        .OrderByDescending(p => p.Rating)
        .FirstOrDefault();
      return post;
    }

    public List<BlogPost> GetAllPosts()
    {
      return _blogContext.BlogPosts
        .OrderByDescending(p => p.Rating)
        .ToList();
    }

    public List<BlogPost> GetRelatedPosts(int id)
    {
      return _blogContext.BlogPosts
        .OrderByDescending(p => p.Rating)
        .Where(p => p.Id != id)
        .ToList();
    }

    public BlogPost GetPostById(int id)
    {
      return _blogContext.BlogPosts.Find(id);
    }

    public void ChangeRating(int id, int increment)
    {
      var post = _blogContext.BlogPosts.Find(id);
      post.Rating += increment;
      _blogContext.BlogPosts.Update(post);
      _blogContext.SaveChanges();
    }
  }
}

Blog/Blog/Models/ErrorViewModel.cs
using System;

namespace Blog.Web.Models
{
  public class ErrorViewModel
  {
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
  }
}

Blog/Blog/ViewModels/HomeViewModel.cs
using System.Collections.Generic;
using Blog.Domain;

namespace Blog.Web.ViewModels
{
  public class HomeViewModel
  {
    public BlogPost BlogPost { get; set; }
    public IEnumerable<BlogPost> RecommendedPosts { get; set; }
  }
}

Blog/Blog/Controllers/CreateAccountController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Web.Controllers
{
  public class CreateAccountController : Controller
  {
    public IActionResult Index()
    {
      return View();
    }
  }
}

Blog/Blog/Controllers/CreatePostController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Domain;
using Blog.Web.Models;

namespace Blog.Web.Controllers
{
  public class CreatePostController : Controller
  {
    private readonly BlogPostRepository _blogPostRepository;

    public CreatePostController(BlogPostRepository blogPostRepository)
    {
      _blogPostRepository = blogPostRepository;
    }
    public IActionResult Index()
    {
      return View();
    }

    [HttpPost]
    public RedirectToActionResult CreatePost(BlogPost post)
    { 
      _blogPostRepository.AddPost(post);
      return RedirectToAction("Index", "Home");
    }
  }
}

Blog/Blog/Controllers/HomeController.cs
using System;
using Blog.Domain;
using Blog.Web.Models;
using Blog.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace Blog.Web.Controllers
{
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;
    private readonly BlogPostRepository _postRepo;

    public HomeController(ILogger<HomeController> logger, BlogPostRepository postRepo)
    {
      _logger = logger;
      _postRepo = postRepo;
    }
   
    public IActionResult Index(int? id)
    {
      var post = id == null 
        ? _postRepo.PostWithHighestRating()
        : _postRepo.GetPostById((int) id);

      if (post == null)
      {
        return View("NoPosts");
      }

      var homeViewModel = new HomeViewModel()
      {
        BlogPost = post,
        RecommendedPosts = _postRepo.GetRelatedPosts(post.Id)
      };

      return View(homeViewModel);
    }

    public RedirectToActionResult UpVote(int id)
    {
      _postRepo.ChangeRating(id, 1);
      return RedirectToAction("Index", new { id });
    }

    public RedirectToActionResult DownVote(int id)
    {
      _postRepo.ChangeRating(id, -1);
      throw new Exception();

      return RedirectToAction("Index", new { id });
    }

    public RedirectToActionResult DeletePost(int id)
    {
      _postRepo.RemovePost(id);
      return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

Blog/Blog/Views/CreateAccount/Index.cshtml
<div class="main-container">
    <article class="create-account">
        <h2>Create Account</h2>
        <form>
            <label class="input-label">Username</label><br>
            <input type="text" class="text-input" /><br>
            <label class="input-label" for="email">E-Mail</label><br>
            <input type="text" class="text-input" />
            <br>
            <label class="input-label" for="password">Password</label><br>
            <input type="password" name="password" class="text-input" />
            <br>
            <label class="input-label">Repeat Password</label><br>
            <input type="password" name="password" class="text-input" />
            <br>
            <button type="submit" class="button">Sign Up</button>
        </form>
    </article>
</div>

Blog/Blog/Views/CreatePost/Index.cshtml
@model Blog.Domain.BlogPost

<div class="main-container">
    <article class="create-post">
        <h2 class="create-post-header">Create New Post</h2>
        <form asp-action="CreatePost" method="post">
            <label>Post Title</label><br>
            <input asp-for="Title" type="text" class="text-input post-title-input" /><br>
            <label>Post</label><br>
            <textarea asp-for="Content" type="text" class="text-input post-input"></textarea><br>
            <div class="post-submit">
                <div>
                    <label for="tag-input">Tags</label><br>
                    <input type="text" class="text-input" id="tag-input" />
                </div>
                <button type="submit" class="button">Submit Post</button>
            </div>
        </form>
    </article>
</div>

Blog/Blog/Views/CreatePost/PostedSuccessfully.cshtml
<h1>Posted Successfully</h1>

Blog/Blog/Views/Home/Index.cshtml
@model Blog.Web.ViewModels.HomeViewModel

<div class="main-container">
    <article>
        <div class="blog-post">
            <div class="post-header">
                <h1>@Model.BlogPost.Title</h1>
                <div class="rating">
                    <strong>@Model.BlogPost.Rating</strong>
                    <a asp-action="UpVote" asp-route-id="@Model.BlogPost.Id" class="rate-arrow">&#8679;</a>
                    <a asp-action="DownVote" asp-route-id="@Model.BlogPost.Id" class="rate-arrow">&#8681</a>
                </div>
            </div>
            <div class="post-info">
                <img src="/img/laura-jones.jpg" alt="picture of author" height="60" width="60" class="author-image" />
                <strong>Laura Jones</strong>
                <span>@Model.BlogPost.PostDate.ToShortDateString()</span>
            </div>
            <p>
                @Html.Raw(Model.BlogPost.Content)
            </p>
        </div>
        <div class="nav-next-post">
            <a asp-action="Index" asp-route-id="@Model.RecommendedPosts.FirstOrDefault()?.Id" class="next-post-button button">Next Post</a>
            <a asp-action="DeletePost" asp-route-id="@Model.BlogPost.Id" class="next-post-button button">Delete Post</a>
        </div>
    </article>

    <aside>
        <div class="recommended-posts">
            <ul>
                @foreach (var post in Model.RecommendedPosts)
                {
                    <partial name="_RecommendedPost" model="post"/>
                }
            </ul>
        </div>
    </aside>
</div>

Blog/Blog/Views/Home/NoPosts.cshtml
<h2>No Posts Found</h2>

Blog/Blog/Views/Home/_RecommendedPost.cshtml
@model Blog.Domain.BlogPost

<li>
    <a asp-controller="Home" asp-action="Index" asp-route-id="@Model.Id" class="rec-post">
        @*<img src="/img/laura-jones.jpg" alt="picture of author" height="30" width="30" class="author-image"/>*@
        <h2>@Model.Title</h2>
        <span class="rec-post-info">
            <span>Rating: @Model.Rating</span>
            <span>Date: @Model.PostDate.ToShortDateString() </span>
        </span>
    </a>
</li>

Blog/Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Code Blog</title>
    <link href="~/css/style.css" rel="stylesheet" />
</head>

<body>
    <div class="main-header-container">
        <header class="main-header">
            <img src="/img/logo.png" alt="logo" height="115" width="115" />
            <nav class="main-navigation">
                <a asp-controller="Home" asp-action="Index">Home</a>
                <a asp-controller="CreatePost" asp-action="Index">Create Post</a>
                @*<a href="#" onclick="openLogin()">Login</a>*@
                <a asp-area="Identity" asp-page="/Account/Register">Register</a>
                @*<a asp-controller="CreateAccount" asp-action="Index">Create Account</a>*@
                <a asp-area="Identity" asp-page="/Account/Login">Login</a>
            </nav>
        </header>
    </div>

    <div class="login-window" id="login-window">
        <h2>Login</h2>
        <form class="login-form">
            <label class="input-label" for="email">E-Mail</label><br>
            <input type="text" class="text-input" id="email" />
            <br>
            <label class="input-label" for="password">Password</label><br>
            <input type="password" name="password" class="text-input" id="password" />
            <br>
            <button type="submit" class="button" value="Login">Login</button>
            <button type="button" class="button" value="Cancel" onclick="closeLogin()">Cancel</button>
        </form>
    </div>

    @RenderBody()

    <footer>
        <a class="privacy-policy" href="#">Privacy Policy</a>
        <span>&copy; Copyright 2021 Code Blog</span>
    </footer>
    @RenderSection("Scripts", required: false)
</body>

<script>
    function closeLogin() {
        document.getElementById('login-window').style.display = 'none';
    }

    function openLogin() {
        document.getElementById('login-window').style.display = 'block';
    }
</script>
</html>